apiVersion: v1
kind: Service
metadata:
  name: k8s-node-app-service
spec:
  selector:
    app: k8s-node-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 3000   # Internal container port
  type: LoadBalancer      # kube-vip will manage the external IP
  loadBalancerIP: 192.168.170.200  # Static IP managed by kube-vip
